name: OpenCPU Cloud Build

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Force Webhook Trigger
        run: |
          curl -v -X POST "https://cloud.opencpu.org/ocpu/webhook?sendmail=true" \
            -H "Content-Type: application/json" \
            -H "X-GitHub-Event: push" \
            -d "{\"repository\": {\"full_name\": \"${{ github.repository }}\", \"url\": \"https://github.com/${{ github.repository }}\"}}"
