name: OpenCPU Cloud Build

on:
  push:
    branches:
      - main

jobs:
  trigger_build:
    runs-on: ubuntu-latest
    steps:
      - name: Force OpenCPU Build via API
        run: |
          curl -v -X POST "https://cloud.opencpu.org/ocpu/library/" \
            -d "package=https://github.com/${{ github.repository }}"
