name: OpenCPU Cloud Build

on:
  push:
    branches:
      - main

jobs:
  trigger_build:
    runs-on: ubuntu-latest
    steps:
      - name: Signal OpenCPU to Rebuild
        run: |
          curl -X POST "https://cloud.opencpu.org/ocpu/webhook?sendmail=true" \
            -H "Content-Type: application/json" \
            -H "X-GitHub-Event: push" \
            -d '{"repository": {"full_name": "${{ github.repository }}"}}'
